# Generated by Django 4.0 on 2024-03-14 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='singlePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('created_at', models.CharField(default='', max_length=100)),
                ('section', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body', models.CharField(default='', max_length=1000000)),
            ],
        ),
    ]
